version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build: ./producer
    image: producer-image
    container_name: producer
    ports:
      - "8081:8081"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  consumer:
    build: ./consumer
    image: consumer-image
    container_name: consumer
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - spring.kafka.consumer.group-id=async
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kafka_demo_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: postgres:13.7-alpine
    container_name: kafka-demo-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=kafka_demo_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root